package studentmanagementsystemq2;

// Class registers the student into the ALU application system.
// Details entered here are used by the student to login in the future.
// Note that this are not the same details used for Application registration. During application,
// a student enters her/his information afresh including grades. See newstudentdetails for more information.

public class newuser {
    // These are the fields required for a new student to register.
    public String FullName; // Column FullName of the SQL Student_credentials
    public String Email; // Column Email of the SQL Student_credentials
    public String StudentPassword; // Column StudentPassword of the SQL Student_credentials
    public String StudentID;  // Autogenerated by mysql table
}
